// Autogenerated with http://www.dotnetwise.com/Code/Externs/
var swfobject = {
    "registerObject": function () {},
    "getObjectById": function () {},
    "embedSWF": function () {},
    "switchOffAutoHideShow": function () {},
    "enableUriEncoding": function () {},
    "ua": {
        "w3": {},
        "pv": {
            "0": {},
            "1": {},
            "2": {}
        },
        "wk": {},
        "ie": {},
        "win": {},
        "mac": {}
    },
    "getFlashPlayerVersion": function () {},
    "hasFlashPlayerVersion": function () {},
    "createSWF": function () {},
    "showExpressInstall": function () {},
    "removeSWF": function () {},
    "createCSS": function () {},
    "addDomLoadEvent": function () {},
    "addLoadEvent": function () {},
    "getQueryParamValue": function () {},
    "expressInstallCallback": function () {},
    "version": {}
}
